### ISSUE TITLE
Holy Water

### ISSUE THREAD

**Issue by iElden** [iElden/BetterBalancedGame#1]
Holy water make your unit regen full life on converted land insead of just adding 10 to the heal value.

**Comment by puj** [comment]
I cannot reproduce this.  Was there potentially a fix?
I tried:
- Healing in my own converted land +25
- Healing in converted suz city state +25
- Healing in open borders of another converted civ +15
- Healing in warred converted civ +15


These values seem correct?

**Comment by puj** [comment]
Was informed by @iElden that this bug apparently only occurs in Multiplayer games. 
So far I tested in hotseat and could not reproduce the bug.

Any videos/stream clips/save games showing the bug would be greatly appreciated.

**Comment by puj** [comment]
Info from Chuck
![image](https://user-images.githubusercontent.com/807352/100935767-d4af8480-34f0-11eb-91ee-329a23b6b46a.png)

The assuming based on this is that the the correct values would be:
- 30 inside city
- 25 inside converted friendly territory
- 10 (same) in neutral
- 15 in enemy converted territory
- 5 in enemy unconverted territory

**Comment by puj** [comment]
Patter Confirm:
The Holy Waters healing bonus increases proportionally to number of districts (including City Center) in your empire.
 + 5 x (# of districts including City Centers)

1 City Center + 1 Holy Site = +10 bonus
For every district after that (including fresh settled cities, it provides +5)

This results in very quickly experienced "Full Healing" from Holy Waters.

I'll update the issue and start working on a fix soon.
