### ISSUE TITLE
Maize icon not working

### ISSUE THREAD

**Issue by clanier9** [iElden/BetterBalancedGame#15]
![image](https://user-images.githubusercontent.com/5515905/100398600-4163e400-3004-11eb-9cf2-9cef379b4e14.png)

**Comment by puj** [comment]
What build is this on?

Bug not present on  https://github.com/iElden/BetterBalancedGame/commit/c8db0ebe6b79f86ac38238155183a1f4c512bf90
![image](https://user-images.githubusercontent.com/807352/100598632-4b852b80-32ff-11eb-91e8-68e656989127.png)


Can this be closed?

**Comment by clanier9** [comment]
Yeah, seemed super odd, may have just been a one time issue. The text looks correct but for some reason it didn't convert it to the actual icon. Probably can be closed.
