### ISSUE TITLE
Mapuche passive don't work vs Heroic age.

### ISSUE THREAD

**Issue by iElden** [iElden/BetterBalancedGame#3]

**Comment by puj** [comment]
Seems like it's not working vs. golden atm either.  I'm looking into this.
![NoBonusVsGolden](https://user-images.githubusercontent.com/807352/100724902-ad0ece00-33c3-11eb-974e-e710d51695d2.PNG)
![GoldenProof](https://user-images.githubusercontent.com/807352/100724911-aed89180-33c3-11eb-9b88-d037f16b9a12.PNG)

**Comment by iElden** [comment]
@puj it's work, it's just not displayed in the damage recap.
This issue is more related to https://github.com/iElden/BetterBalancedGame/issues/6

**Comment by puj** [comment]
Okay, thanks @iElden I'll look into the indicated on #6 

I don't seem to find a streamlined way of setting up the test scenario using FireTuner (setting the age of a Player to Heroic/Dark/Golden).  Is preparing a saved game using the +/- era score button the way to go here?
