### ISSUE TITLE
UI/Text: Norway Berserker, don't show "+0 when defending" in tooltip

### ISSUE THREAD

**Issue by puj** [iElden/BetterBalancedGame#56]
`//base.sql`
![image](https://user-images.githubusercontent.com/807352/102711689-df716400-42bb-11eb-961a-25abc5eaaba7.png)

Probably just remove `UNIT_WEAK_WHEN_ATTACKING`
![image](https://user-images.githubusercontent.com/807352/102711707-fe6ff600-42bb-11eb-9f05-e3b6eb9fd243.png)

**Comment by iElden** [comment]
Berserker modified so this issue is no longer an issue.
