### ISSUE TITLE
Translate warning (in the wrong place).

### ISSUE THREAD

**Issue by e-ahmedwaleed** [iElden/BetterBalancedGame#71]
A little typo at lang/korean.xml, causing the TO TRANSLATE warning to appear for English instead of Korean.

![image](https://user-images.githubusercontent.com/48316191/103314401-a9568180-4a2b-11eb-8bb4-f4de37085716.png)

**Comment by EngAhmedWaleed** [comment]
The problem is at line 128

**Comment by iElden** [comment]
Fixed
